spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8001
spring:
  profiles: dev #开发环境
  application:
    name: USER-PROVIDER
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip
---
server: 
  port: 8847
spring:
  profiles: test #测试环境
  application:
    name: USER-PROVIDER-TEST
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip
